addons:
  apt:
    packages:
    - ocaml
    - curl
    - build-essential
    - m4
    - pkg-config
    - zlib1g-dev
    - libgmp-dev
    - libssl-dev
    - libboost-system-dev
    - aspcud
cache:
  directories:
  - $HOME/.opam
sudo: required
branches:
  only: 
    - master
before_install:
- sh <(curl -sL https://raw.githubusercontent.com/ocaml/opam/master/shell/install.sh)
- opam init -y
- opam switch -y 4.06.1
- opam install -y ocaml-migrate-parsetree core cryptokit ppx_sexp_conv yojson batteries angstrom hex ppx_deriving ppx_deriving_yojson menhir oUnit dune stdint fileutils ctypes ctypes-foreign bisect_ppx
- eval `opam config env`
- rm $HOME/.opam/log/*
script:
- make test
- make coveralls
